# Generated by Django 6.1 on 2026-09-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='login_cred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='remedies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_email', models.EmailField(max_length=254)),
                ('Name', models.TextField()),
                ('Issues', models.TextField()),
                ('Solution', models.TextField()),
                ('img', models.FileField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/')),
                ('Benefits', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
            ],
        ),
    ]
