# Generated by Django 6.1 on 2026-09-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
