# Generated by Django 6.1 on 2026-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Contact',
            field=models.CharField(max_length=15),
        ),
    ]
