# Generated by Django 6.1 on 2026-09-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedic_app', '0002_admin_alter_register_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='remedies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Issues', models.TextField()),
                ('img', models.FileField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/')),
                ('Benefits', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
