# Generated by Django 6.1 on 2026-09-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedic_app', '0003_remedies'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedies',
            name='Solution',
            field=models.TextField(default='Solution'),
            preserve_default=False,
        ),
    ]
