# Generated by Django 6.1 on 2026-09-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedic_app', '0004_remedies_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedies',
            name='status',
            field=models.TextField(default='PENDING'),
        ),
        migrations.AddField(
            model_name='remedies',
            name='user_email',
            field=models.EmailField(default='admin', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedies',
            name='user_name',
            field=models.TextField(default='admin'),
            preserve_default=False,
        ),
    ]
